using System;
using UnityEngine;

namespace ProjectAegis.Systems.Idle
{
    /// <summary>
    /// Represents a single production line that generates money over time.
    /// Each line is associated with a specific drone model and has its own
    /// efficiency and production rate.
    /// </summary>
    [Serializable]
    public class ProductionLine
    {
        [Header("Identity")]
        [Tooltip("Unique identifier for this production line")]
        public string lineId;
        
        [Tooltip("ID of the drone model being produced")]
        public string droneModelId;
        
        [Header("Production")]
        [Tooltip("Base money generation rate per minute")]
        public float baseProductionRate;
        
        [Tooltip("Current efficiency multiplier (affected by upgrades, events, etc.)")]
        public float efficiencyMultiplier = 1.0f;
        
        [Tooltip("Whether this production line is currently active")]
        public bool isActive = true;
        
        [Header("Timing")]
        [Tooltip("When this production line was started")]
        public DateTime startTime;
        
        [Tooltip("Total accumulated production time in minutes")]
        public float totalProductionMinutes;
        
        [Header("State")]
        [Tooltip("Partial progress towards next money tick (0-1)")]
        public float partialProgress;
        
        [Tooltip("Total money generated by this line since creation")]
        public float lifetimeEarnings;

        /// <summary>
        /// Event fired when this line produces money
        /// </summary>
        public event Action<ProductionLine, float> OnProductionTick;

        /// <summary>
        /// Creates a new production line
        /// </summary>
        public ProductionLine(string droneModelId, float baseRate, string lineId = null)
        {
            this.lineId = lineId ?? Guid.NewGuid().ToString("N")[..8];
            this.droneModelId = droneModelId;
            this.baseProductionRate = baseRate;
            this.efficiencyMultiplier = 1.0f;
            this.isActive = true;
            this.startTime = DateTime.UtcNow;
            this.totalProductionMinutes = 0;
            this.partialProgress = 0;
            this.lifetimeEarnings = 0;
        }

        /// <summary>
        /// Gets the effective production rate (base rate × efficiency)
        /// </summary>
        public float GetEffectiveRate()
        {
            if (!isActive) return 0;
            return baseProductionRate * efficiencyMultiplier;
        }

        /// <summary>
        /// Calculates money earned over a duration
        /// </summary>
        public float CalculateEarnings(TimeSpan duration)
        {
            if (!isActive || baseProductionRate <= 0) return 0;
            
            float minutes = (float)duration.TotalMinutes;
            return GetEffectiveRate() * minutes;
        }

        /// <summary>
        /// Calculates money earned over a duration, accounting for partial progress
        /// </summary>
        public float CalculateEarningsWithPartial(TimeSpan duration, out float newPartialProgress)
        {
            if (!isActive || baseProductionRate <= 0)
            {
                newPartialProgress = partialProgress;
                return 0;
            }

            float minutes = (float)duration.TotalMinutes;
            float effectiveRate = GetEffectiveRate();
            
            // Calculate how many "ticks" of production we get
            // A "tick" is 1 minute of production
            float totalProgress = partialProgress + minutes;
            float fullTicks = Mathf.Floor(totalProgress);
            newPartialProgress = totalProgress - fullTicks;
            
            return fullTicks * effectiveRate;
        }

        /// <summary>
        /// Simulates production for offline calculation
        /// </summary>
        public float SimulateOfflineProduction(TimeSpan duration)
        {
            float earnings = CalculateEarnings(duration);
            
            if (earnings > 0)
            {
                lifetimeEarnings += earnings;
                totalProductionMinutes += (float)duration.TotalMinutes;
            }
            
            return earnings;
        }

        /// <summary>
        /// Updates partial progress for accurate offline calculation
        /// </summary>
        public float UpdateAndCalculate(TimeSpan duration)
        {
            float newPartial;
            float earnings = CalculateEarningsWithPartial(duration, out newPartial);
            partialProgress = newPartial;
            
            if (earnings > 0)
            {
                lifetimeEarnings += earnings;
                totalProductionMinutes += (float)duration.TotalMinutes;
                OnProductionTick?.Invoke(this, earnings);
            }
            
            return earnings;
        }

        /// <summary>
        /// Sets the efficiency multiplier
        /// </summary>
        public void SetEfficiency(float multiplier)
        {
            efficiencyMultiplier = Mathf.Max(0, multiplier);
        }

        /// <summary>
        /// Multiplies the efficiency by a factor
        /// </summary>
        public void MultiplyEfficiency(float factor)
        {
            efficiencyMultiplier *= factor;
            efficiencyMultiplier = Mathf.Max(0, efficiencyMultiplier);
        }

        /// <summary>
        /// Activates the production line
        /// </summary>
        public void Activate()
        {
            isActive = true;
        }

        /// <summary>
        /// Deactivates the production line
        /// </summary>
        public void Deactivate()
        {
            isActive = false;
        }

        /// <summary>
        /// Gets the production rate per second (for UI display)
        /// </summary>
        public float GetRatePerSecond()
        {
            return GetEffectiveRate() / 60f;
        }

        /// <summary>
        /// Gets the production rate per hour (for UI display)
        /// </summary>
        public float GetRatePerHour()
        {
            return GetEffectiveRate() * 60f;
        }

        /// <summary>
        /// Gets a display name for this production line
        /// </summary>
        public string GetDisplayName()
        {
            return $"Line {lineId} - {droneModelId}";
        }

        /// <summary>
        /// Resets the production line statistics
        /// </summary>
        public void ResetStats()
        {
            totalProductionMinutes = 0;
            partialProgress = 0;
            lifetimeEarnings = 0;
        }

        /// <summary>
        /// Creates a copy of this production line for save purposes
        /// </summary>
        public ProductionLine Clone()
        {
            return new ProductionLine(droneModelId, baseProductionRate, lineId)
            {
                efficiencyMultiplier = efficiencyMultiplier,
                isActive = isActive,
                startTime = startTime,
                totalProductionMinutes = totalProductionMinutes,
                partialProgress = partialProgress,
                lifetimeEarnings = lifetimeEarnings
            };
        }
    }
}
